name: External tests

on:
  schedule:
    - cron: '0 14 * * *'  # Runs at 14:00 CET daily
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        repo:
           - 'eonist/FileSugar'
           - 'eonist/JSONSugar'
           - 'eonist/ClipboardSugar'
           - 'sentryco/Telemetric'
           - 'sentryco/CrashKit'
           - 'sentryco/NetTime'
           - 'sentryco/UpgradeAlert'
           - 'sentryco/Logger'
           - 'eonist/With'
           - 'eonist/WizardHelper'
           - 'eonist/TestRunner'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ matrix.repo }}

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.9'

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
