name: External tests

on:
  schedule:
    - cron: '0 14 * * *'  # Runs at 14:00 CET daily
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        repo:
           - 'eonist/FileSugar'
           - 'eonist/JSONSugar'
           - 'eonist/ClipboardSugar'
           - 'sentryco/Telemetric'
           - 'sentryco/CrashKit'
           - 'sentryco/NetTime'
           - 'sentryco/UpgradeAlert'
           - 'sentryco/Logger'
           - 'eonist/With'
           - 'eonist/WizardHelper'
           - 'eonist/TestRunner'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ matrix.repo }}

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.9'

    - name: Build
      run: swift build -v

    - name: Check for tests
      id: check_tests
      run: |
        # Check if any test files exist in the Sources directory.
        # This assumes a standard Swift package structure where tests are located in a directory
        # that contains "Tests" in its name (e.g., Sources/MyPackageTests/).
        # The ls command searches for Swift files (*.swift) within such directories.
        # The output is redirected to /dev/null to suppress the output of the ls command.
        # If any files are found, the has_tests output is set to true; otherwise, it's set to false.
        if ls Sources/*Tests*/*.swift > /dev/null 2>&1; then
          echo "::set-output name=has_tests::true"
        else
          echo "::set-output name=has_tests::false"
        fi

    - name: Run tests
      if: steps.check_tests.outputs.has_tests == 'true'
      run: swift test -v

      